### ISSUE TITLE
Disable root logger in consumer

### ISSUE THREAD

**Issue by larsderidder** [coleifer/huey#437] opened 2019-07-31 13:43 UTC
I'm converting an existing code base to use Huey. One thing I'm running into is duplicate logs. In some Python modules I create a new logger with the name of the file, and attach a handler to it. However, the Huey consumer already sets up a handler on the root logger (in consumer_options.py, line 166 and before). So when I run any code using my logger, I get both logs.

I don't see any way to override this behaviour. I do see that the setup_logger function on line 144 in the same file does accept a logger, but it's never passed in. Regardless, I don't see how I would access this anyway from the consumer.

My preferred behaviour is that there is a way to have no handler added to the root logger, only a handler to the Huey logger which logs Huey stuff. Given that most of the logging appears to be done on specific loggers for Huey, I wouldn't expect this to be too impactful. The resulting behaviour would be like "semi-quiet" or "system-only".

Would like to hear your thoughts. In the mean time I solved it by creating a child of the huey.consumer logger depending on an environment variable I pass to the process running the consumer, which works but I then lose control over formatting the log statements (which is not a huge deal in this case luckily).

**Comment by coleifer** [comment] 2019-07-31 14:47
Yeah, you're right -- that should be fixed.

**Closed** 2019-07-31 14:49 UTC

**Comment by MonsieurV** [comment] 2019-08-21 17:37
Hey @coleifer,

I'm running in a similar issue. Using the Django integration, with the following configs:

```python
HUEY = {
    "name": "task",
    "huey_class": "huey.PriorityRedisHuey",
    "connection": {"connection_pool": redis_huey_pool},
    "consumer": {"workers": 64, "worker_type": "greenlet"},
    "utc": True,
    "immediate": False,
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "verbose": {
            "format": "@{} [%(levelname)s %(module)s:%(threadName)s] %(message)s".format(
                env_variables["env_name"]
            )
        },
        "simple": {"format": "%(levelname)s: %(message)s"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
        },
    },
    "filters": {
        "require_debug_true": {"()": "django.utils.log.RequireDebugTrue"},
        "require_debug_false": {"()": "django.utils.log.RequireDebugFalse"},
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": True,
        },
        "django.request": {
            "handlers": ["mail_admins"],
            "filters": ["require_debug_false"],
            "level": "ERROR",
            "propagate": False,
        },
        "huey": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "DEBUG"),
            "propagate": False,
        },
    },
}
```

I got duplicated log entries: one from the `console` handler configured through Django `LOGGING`, one from the handler hard-coded in `consumer_options.py`:

https://github.com/coleifer/huey/blob/e091a5f9a4c23a7cfb96ac96215f04cec8177e78/huey/consumer_options.py#L165

I'm currently unable to disable the handler from `consumer_options.py` and I'm not sure how it could be done. Any hints?

**Comment by coleifer** [comment] 2019-08-24 21:04
Perhaps you should not try to manage the huey logger via the dictionary of settings, and instead just use the consumer options / command switches to handle it.

**Comment by MonsieurV** [comment] 2019-08-24 21:52
> Perhaps you should not try to manage the huey logger via the dictionary of settings, and instead just use the consumer options / command switches to handle it.

That what I was trying to do, but without success (I could add the `console` handler specified, but not remove the `handler` previously added by Huey at startup in `consumer_options.py`).

See that part of my Django config:

```python
LOGGING = {
   ...
   "loggers": {
        "huey": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "DEBUG"),
            "propagate": False,
        },
   ...
```

Should I do a PR adding an option to Huey for not adding default logging settings (the formater + handler set in `setup_logger`)?

That is, disabling the code here:
https://github.com/coleifer/huey/blob/e091a5f9a4c23a7cfb96ac96215f04cec8177e78/huey/consumer_options.py#L144

**Comment by coleifer** [comment] 2019-08-24 22:01
I'm suggesting remove all the "huey" shit from your LOGGING setting.

**Comment by MonsieurV** [comment] 2019-08-25 12:31
Hum, ok, then I only got the default Huey logging handler and formatter, which is not the effect I intend: I want to disable Huey default handler and formatter to add my own.

With the configuration above, I'm able to add my own handler and formatter (_"the huey shit"), but unable to disable the default Huey handler and formatter.

The effect of that is duplicate logging, eg.:

```
task_consumer_1  | @dev [INFO api:DummyThread-4] mypackage.tasks.my_task: daaaaa49-ddc7-46ee-960d-50ef54dcdd05 executed in 1.209s
task_consumer_1  | [2019-08-25 14:00:13,591] INFO:huey:DummyThread-4:mypackage.tasks.my_task: daaaaa49-ddc7-46ee-960d-50ef54dcdd05 executed in 1.209s
```

1st line is the handler I added with my `LOGGING` settings, 2nd line is the handler added by default by `huey_consumer.py`, which I would like to disable (to only have the custom log formatting used in my project).

**Comment by MonsieurV** [comment] 2019-08-25 12:39
Here a demo project to see the effect of duplicate logging: https://github.com/MonsieurV/huey-config-logging

When running, we get the following output, which show the duplicate logging:

```
make run-demo
pipenv run huey_consumer.py demo.huey -w 2
[INFO:huey.consumer:MainThread] Huey consumer started with 2 thread, PID 28820 at 2019-08-25 12:34:37.386038
[2019-08-25 14:34:37,386] INFO:huey.consumer:MainThread:Huey consumer started with 2 thread, PID 28820 at 2019-08-25 12:34:37.386038
[INFO:huey.consumer:MainThread] Scheduler runs every 1 second(s).
[2019-08-25 14:34:37,386] INFO:huey.consumer:MainThread:Scheduler runs every 1 second(s).
[INFO:huey.consumer:MainThread] Periodic tasks are enabled.
[2019-08-25 14:34:37,386] INFO:huey.consumer:MainThread:Periodic tasks are enabled.
[INFO:huey.consumer:MainThread] The following commands are available:
+ demo.add
+ demo.add_periodic
[2019-08-25 14:34:37,386] INFO:huey.consumer:MainThread:The following commands are available:
+ demo.add
+ demo.add_periodic
[INFO:huey.consumer.Scheduler:Scheduler] Enqueueing periodic task demo.add_periodic: 8b19a43b-ae7f-47f6-a3d1-47aa004a4ca2.
[2019-08-25 14:34:37,387] INFO:huey.consumer.Scheduler:Scheduler:Enqueueing periodic task demo.add_periodic: 8b19a43b-ae7f-47f6-a3d1-47aa004a4ca2.
[INFO:huey:Worker-2] Executing demo.add_periodic: 8b19a43b-ae7f-47f6-a3d1-47aa004a4ca2
[2019-08-25 14:34:37,488] INFO:huey:Worker-2:Executing demo.add_periodic: 8b19a43b-ae7f-47f6-a3d1-47aa004a4ca2
[INFO:huey:Worker-1] Executing demo.add: 5c768e58-5098-4185-a14a-08cdb6bcabf7
[2019-08-25 14:34:37,490] INFO:huey:Worker-1:Executing demo.add: 5c768e58-5098-4185-a14a-08cdb6bcabf7
[INFO:huey:Worker-1] demo.add: 5c768e58-5098-4185-a14a-08cdb6bcabf7 executed in 0.000s
[2019-08-25 14:34:37,490] INFO:huey:Worker-1:demo.add: 5c768e58-5098-4185-a14a-08cdb6bcabf7 executed in 0.000s
[INFO:huey:Worker-2] Add 41 + 1 = 42
[2019-08-25 14:34:37,589] INFO:huey:Worker-2:Add 41 + 1 = 42
```

Can you show how we can disable Huey default handler to only have our own? (so we can have complete control over the log formatting)

https://github.com/MonsieurV/huey-config-logging/blob/master/demo.py#L8

**Comment by coleifer** [comment] 2019-08-25 20:11
I've added a check if the logger has any handlers in the mgmt command, and if so will not call setup_logger().

**Comment by MonsieurV** [comment] 2019-08-26 11:32
Thanks @coleifer, it works

Also thanks for the great library ; it really does the job! :) :raised_hands:

**Comment by JSalter02** [comment] 2019-09-04 19:19
What about for people not using Django? Similar fix possible?
I'm also getting double logs due to internal/external logging simultaneously:

```
[2019-09-04 15:17:17,084] INFO:huey.consumer:MainThread:All workers have stopped.
2019-09-04 15:17:17,084 - consumer(401) - INFO - All workers have stopped.
[2019-09-04 15:17:17,084] INFO:huey.consumer:MainThread:Consumer exiting.
2019-09-04 15:17:17,084 - consumer(440) - INFO - Consumer exiting.
```
I've updated to 2.1.2.

**Comment by coleifer** [comment] 2019-09-04 19:57
Ordinary Python apps don't typically use the same massive/global logging configuration approach that you see in Django.

**Comment by MonsieurV** [comment] 2019-09-04 20:15
@JSalter02 for the moment, you can for e.g. [remove the Huey custom log handler](https://github.com/MonsieurV/huey-config-logging/blob/master/huey_custom_consumer.py#L13) after the consumer startup (you can do that by doing your own [`huey_consumer.py`](https://github.com/MonsieurV/huey-config-logging/blob/master/huey_custom_consumer.py#L57) or maybe launching a one-shot task right after the consumer init).

**Comment by JSalter02** [comment] 2019-09-04 20:30
Hmm. I'm not sure exactly what's going on to cause it, but maybe it has something to do with me using logging.config.dictConfig to set up logging interfering with your own setup?

In any case, it's probably my problem, not yours. But a hook to disable your logging setup and let log calls be handled by the external application wouldn't hurt.

**Comment by larsderidder** [comment] 2019-10-02 09:58
Thanks to @MonsieurV I came up with a pretty decent solution (without having to make a custom `huey_consumer.py` thankfully.

My previous workaround was to set an environment variable with the static name of the logger to use (I used 'huey.consumer'), and then I modified my own get_logger function to just return the logger with that name, regardless of the argument (I usually pass `__name__` into get_logger).

I modified this to using a huey startup function @huey.on_startup() (basically a one-shot task), to call a variant of the disable_huey_custom_handler that was linked to:

```
@huey.on_startup()
def startup():
    disable_huey_custom_handler()

def disable_huey_custom_handler():
    huey_logger = logging.getLogger("huey")
    if huey_logger.handlers:
        logger.info(
            f"Handlers in huey_customer_consumer.py (before removing huey default handler): {huey_logger.handlers}"
        )
        huey_logger.handlers.pop()
```

The if-check on the handlers was necessary because I use gevent, so multiple workers will execute this startup script.

Works like a charm!

**Comment by coleifer** [comment] 2019-10-02 13:31
For Django users, huey only sets up the logging handler if the logger has no configured handlers.

Huey logs to a namespace, as well -- it does not log to the root logger -- so presumably if you're seeing duplication it's because of poorly organized logging in your own app.

**Comment by JSalter02** [comment] 2019-10-02 14:10
I set up a barebones Django app, added huey to INSTALLED_APPS, created a tasks.py file, and attempted to customize huey's log output with the following settings:

```
from huey import SqliteHuey

HUEY_DB_PATH = './taskqueue.db'
HUEY = SqliteHuey(filename=HUEY_DB_PATH,immediate=False)

LOGGING = {
    'version': 1,
    'formatters': {
        'console': {
            'format': '%(asctime)s %(name)-12s:%(lineno)d %(levelname)-8s %(message)s',
        },
    },
    'handlers': {
        'custom': {
            'class': 'logging.StreamHandler',
            'formatter': 'console'
        },
    },
    'loggers': {
        'huey.consumer': {
            'handlers': ['custom'],
            'level': 'INFO',
        },
    },
}
```

I run the consumer with:
`python manage.py run_huey -w 1`

The output I get is:
```
2019-10-02 10:08:46,414 huey.consumer:356 INFO     Huey consumer started with 1 thread, PID 25528 at 2019-10-02 14:08:46.414230
[2019-10-02 10:08:46,414] INFO:huey.consumer:MainThread:Huey consumer started with 1 thread, PID 25528 at 2019-10-02 14:08:46.414230
2019-10-02 10:08:46,415 huey.consumer:358 INFO     Scheduler runs every 1 second(s).
[2019-10-02 10:08:46,415] INFO:huey.consumer:MainThread:Scheduler runs every 1 second(s).
2019-10-02 10:08:46,416 huey.consumer:360 INFO     Periodic tasks are enabled.
[2019-10-02 10:08:46,416] INFO:huey.consumer:MainThread:Periodic tasks are enabled.
2019-10-02 10:08:46,416 huey.consumer:368 INFO     The following commands are available:
+ testapp.tasks.every_three_minutes
[2019-10-02 10:08:46,416] INFO:huey.consumer:MainThread:The following commands are available:
+ testapp.tasks.every_three_minutes
2019-10-02 10:08:49,038 huey.consumer:417 INFO     Received SIGINT
[2019-10-02 10:08:49,038] INFO:huey.consumer:MainThread:Received SIGINT
2019-10-02 10:08:49,039 huey.consumer:394 INFO     Shutting down gracefully...
[2019-10-02 10:08:49,039] INFO:huey.consumer:MainThread:Shutting down gracefully...
2019-10-02 10:08:49,370 huey.consumer:401 INFO     All workers have stopped.
[2019-10-02 10:08:49,370] INFO:huey.consumer:MainThread:All workers have stopped.
2019-10-02 10:08:49,372 huey.consumer:440 INFO     Consumer exiting.
[2019-10-02 10:08:49,372] INFO:huey.consumer:MainThread:Consumer exiting.
```

What's incorrect with this approach? It appears to me that huey is logging on its own regardless of django settings.

**Comment by coleifer** [comment] 2019-10-02 14:19
What huey version are you using?

**Comment by JSalter02** [comment] 2019-10-02 14:25
```
$ pip show huey
Name: huey
Version: 2.1.2
Summary: huey, a little task queue
```

**Comment by coleifer** [comment] 2019-10-02 14:25
Ahh, I see the issue -- the consumer looks for handlers bound to "huey" namespace and you've specified "huey.consumer". Just modify your example to "huey" and that should resolve the duplication.

**Comment by JSalter02** [comment] 2019-10-02 14:29
Confirmed.

I suggest you look for huey* rather than just huey, that way developers can customize different levels for different parts. I might want more detail from the consumer, and just errors from the rest, etc.

**Comment by coleifer** [comment] 2019-10-02 14:37
> I suggest you look for huey*

I don't think that python's logging facility has any way to do this. The management command uses `logging.getLogger('huey')` and then checks the returned logger if it has any handlers. How would one scan the entire namespace?

**Comment by JSalter02** [comment] 2019-10-02 16:02
[name for name in logging.root.manager.loggerDict if name.startswith('huey')]

**Comment by coleifer** [comment] 2019-10-02 16:25
![im-76a73f7f4d](https://user-images.githubusercontent.com/119974/66062631-609dd900-e507-11e9-8da2-9d5395b543cc.png)

I'm gonna hard pass on that

**Comment by JSalter02** [comment] 2019-10-02 16:33
Heh. That's your choice.

It looks scarier than it is. "root" here refers to the root logging level, not some weird internal thing.
You could use `logging.Logger.manager.loggerDict` instead if it makes you feel better.

**Comment by LaBlazer** [comment] 2020-03-08 00:28
> ![im-76a73f7f4d](https://user-images.githubusercontent.com/119974/66062631-609dd900-e507-11e9-8da2-9d5395b543cc.png)
> 
> I'm gonna hard pass on that

Why?

**Comment by rafi** [comment] 2020-03-11 19:21
So why are the logs duplicated in the fist place? I don't use Django at all, but I'd like to set Huey's log-level at INFO and my application at DEBUG. What's the reason I need to `pop()` huey's logger?

```py
import atexit
import logging
from huey.consumer_options import ConsumerConfig

from my.super.app.queue import huey


logging.basicConfig(level=logging.DEBUG)

logger = logging.getLogger('my.super.app')

huey_logger = logging.getLogger('huey')
huey_logger.setLevel(logging.INFO)

config = ConsumerConfig(**ctx.options)
config.validate()
config.setup_logger(huey_logger)

# See https://github.com/coleifer/huey/issues/437
huey_logger.handlers.pop()

atexit.register(shutdown_handler, ctx)

consumer = huey.create_consumer(**config.values)
consumer.run()
```

**Comment by coleifer** [comment] 2020-03-11 22:06
@rafi - I'm not sure I follow. Are you seeing log duplication? Which logs are duplicated? Are you sure your app is logging to your "my.super.app" namespace and not the root logger?

**Comment by larsderidder** [comment] 2020-03-12 08:40
@rafi You could try adding `logger.propagate = False` under the `logger = logging.getLogger('my.super.app')` line.

**Comment by rafi** [comment] 2020-03-12 14:31
@coleifer The application is mostly using the `my.super.app` logger, but, many classes are instantiating their own logger with `self.logger = logging.getLogger(__name__)` as-well.

Regarding duplication, everything in log (stdout) is duplicated twice, Huey's output and entire application. Per my code snippet above, `huey_logger.handlers.pop()` solves it and allows me to achieve INFO logging in Huey, and DEBUG logging in the entire application. I'll try @larsderidder 's solution later, looks cleaner.

I'm not well-versed in the internals and stack management of the `logging` library, but Huey's logging behavior confused me for few hours to no avail. I'm also using Sentry's logging transport client, the [old client](https://github.com/getsentry/raven-python/blob/master/raven/handlers/logging.py#L106) seem to use the technique people offered here, but the [new client](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/logging.py#L44) seem to offer bindings to its logging hooks, it might be a better structural way to manage the logger in a same manner. Not sure :o)

**Comment by coleifer** [comment] 2020-03-12 15:49
The problem is that by calling `logging.basicConfig` you are adding an additional stream handler.

Per Python docs:

>Does basic configuration for the logging system by creating a StreamHandler with a default Formatter and adding it to the root logger. The functions debug(), info(), warning(), error() and critical() will call basicConfig() automatically if no handlers are defined for the root logger.

**Comment by rafi** [comment] 2020-03-12 16:13
The "outer" service-tier, such as CLI and HTTP handlers, light-weight dev server mode, etc., they all use that root logger to report low-level issues with i/o, and import it as an object from a lil' module:

```py
import logging

logging.basicConfig(
    level=logging.DEBUG,
    format='[%(asctime)s] [%(process)s] [%(levelname)s]'
           ' [%(name)s] %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S')

LOGGER = logging.getLogger('my.duper.super.buper.gluper.app')
```

"Inner" classes and entities bootstrap their own loggers like mentioned before, unrelated to this root logger, however the `basicConfig` settings are enforced through-out. So by removing it I'll lose the ability of "umbrella" settings such as `level` and `format`, and unifying my outer application i/o logging ability.

**Comment by coleifer** [comment] 2020-03-12 17:46
@rafi - I'd suggest you read the code for `logging.basicConfig` - I believe it will clear-up your confusion.

**Comment by mindojo-victor** [comment] 2020-03-25 17:19
My workaround to avoid Huey's logging configuration:
```python
import huey.consumer_options
huey.consumer_options.ConsumerConfig.setup_logger = lambda *args, **kwargs: None
```

**Comment by radusuciu** [comment] 2021-08-23 19:28
Also hitting the issue of double logging with Django. Here's my logging config:

```python

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'class': 'logging.Formatter',
            'format': '%(asctime)s\t%(levelname)s\t%(filename)s:%(lineno)d\t%(message)s',
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'INFO',
            'formatter': 'standard',
            # by default, StreamHandler logs to stdderr
            'stream': 'ext://sys.stdout',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'huey': {
        'handlers': ['console'],
        'level': 'INFO',
        'propagate': False
    },
    'django': {
        'handlers': ['console'],
        'level': 'INFO',
    }
}
```

Python 3.9.6, huey 2.4.0, Django 3.1.13. It bears mentioning that I'm using [`django_huey`](https://github.com/gaiacoop/django-huey) for multi-queue support. `django-huey` also [disables logging if there are any attached handlers](https://github.com/gaiacoop/django-huey/blob/e24255f7280f1185050abfecc0126ac5a176bc6c/django_huey/management/commands/djangohuey.py#L84-L88).

I don't have time to go into this further (and in my case maybe `django-huey` is a better forum), but my best guess would be that [django logging isn't configured](https://github.com/django/django/blob/ed317e79e355bd3aacb1393b821df7b1a7267ebc/django/__init__.py#L19) from the logging dict when the huey consumer is run.

The workaround posted above:
```python
import huey.consumer_options
huey.consumer_options.ConsumerConfig.setup_logger = lambda *args, **kwargs: None
```

worked for me. I inserted this code right after my Django logging config.
