### ISSUE TITLE
Tasks Scheduling Tasks Run Immediately?

### ISSUE THREAD

**Issue by chayim** [coleifer/huey#152] opened 2016-06-07 20:56 UTC
I have a periodic task that runs at 2 minutes past the hour - every hour (see below). It's also triggered by a django management command - which is the issue.  The task loader in turn schedules a series of tasks - as below.  Unfortunately, when those tasks are scheduled in the future, they execute immediately, rather than being sent off to the task queue.  The example below can reproduce this.
```python
#### foo/tasks.py ####
@db_task
def somefunc(val):
    print 'hi'

@db_periodic(crontab('2 * * * *'))
def load_thing():
     # dothings
     future = datetime.datetime.now() + datetime.timedelta(seconds=3600)
     somefunc.schedule(args=(1,), eta=future)

### django management command
import os
import sys 
from django.core.management.base import BaseCommand
from foo.tasks import load_thing

class Command(BaseCommand):
    help = "A script to schedule integration refreshes"

    def handle(self, *args, **kwargs):
        load_integrations()
```

**Comment by chayim** [comment] 2016-06-07 21:10
It equally occurs when specifying a delay, rather than an eta.  For fun - I have confirmed that (future - datetime.datetime.now()).seconds is working as it ought be, as I used for delay.

**Comment by coleifer** [comment] 2016-06-07 21:38
You need to use `datetime.datetime.utcnow()` most likely. Will you please check and verify?

**Comment by chayim** [comment] 2016-06-08 01:33
Unfortunately, that's not it.

I've also gone down the path of:
from django.utils import timezone
now = timezone.now()

When looking at the time difference, it's definitely correct - in that the correct number of seconds come back from timedelta.

**Comment by coleifer** [comment] 2016-06-08 01:40
Did you try that, though?

**Comment by chayim** [comment] 2016-06-08 01:41
I did.

**Comment by coleifer** [comment] 2016-06-08 01:42
How are you running the consumer, and how are you instantiating Huey object?

**Comment by coleifer** [comment] 2016-06-08 01:45
Oh, and can you turn on logging and send me some of the logs demonstrating
the issue?

**Comment by chayim** [comment] 2016-06-08 01:52
Sure.

To start, I'm running the consumer via django (manage.py run_huey) with the following settings:
HUEY = { 
    'name': 'taggity',
    'connection': {'host': 'localhost', 'port': 6379},
    'consumer': {'workers': 20, 'worker_type': 'threads'},
}

Attached is the barebones django management command I crafted to pull this together, along with the associated tasks.

[tmp.zip](https://github.com/coleifer/huey/files/303863/tmp.zip)

**Comment by chayim** [comment] 2016-06-08 01:54
I should also mention - this is huey latest from pypi, django latest (1.9.7). Redis latest as well.

**Comment by coleifer** [comment] 2016-06-08 02:28
Hey @chayim -- please take the extra moment or two to properly format your code samples. I've fixed the code in the issue report, you can see how I've done it by clicking the "Edit" icon.

**Comment by chayim** [comment] 2016-06-08 02:30
Apologies @coleifer - markdown fail on my part.  I appreciate your looking into this!

**Comment by coleifer** [comment] 2016-06-08 03:10
No worries! Hmm... so I'm just wanting to make sure I understand exactly what you're seeing. Can you let me know if I've got it right?

Let's say I have a periodic task, `perform_checks` that runs every 3 minutes. I've also got a plain old task, `check_item` that is enqueued by the `perform_checks` periodic task. The logic is:

* every 3 minutes, `perform_checks` will run. When it runs, it schedules 3 instances of `check_item()` at the following times:
    * now + 0 seconds
    * now + 60 seconds
    * now + 120 seconds

You're noticing that instead of the `check_item` sub-tasks running at the above intervals, they all execute immediately?

If that's the case, then I'm unfortunately not able to reproduce it locally. To test it, I went into the `examples/simple` dir in the huey source tree and added the following to `tasks.py`:

```python
import datetime

@huey.periodic_task(crontab(minute='*/3'))
def perform_checks():
    now = datetime.datetime.now()
    for i in range(3):
        eta = now + datetime.timedelta(seconds=(60 * i))
        print 'scheduling check_item(%s)' % i
        check_item.schedule(args=(now, '%s mins later' % i), eta=eta)
    print 'done enqueueing tasks'

@huey.task()
def check_item(caller_ts, msg):
    print 'check item: %s, %s' % (caller_ts, msg)
```

I then fired up the consumer (`./cons.sh`) and watched the output, which appears correct. You'll notice that the periodic task (`perform_checks`) runs at 22:00. The first check_item call (now + 0 seconds) runs a few milliseconds later. Then, nothing happens unti 22:01, when the second check_item call (now + 60) runs. Ditto at 22:02. At 22:03 `perform_check` runs again and the pattern repeats.

```
[2016-06-07 22:00:38,727] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_perform_checks: queuecmd_perform_checks
scheduling check_item(0)
scheduling check_item(1)
scheduling check_item(2)
done enqueueing tasks

[2016-06-07 22:00:38,730] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_check_item: 0a860431-a844-434c-b103-71ce20f66d3a @2016-06-08 03:00:38
check item: 2016-06-07 22:00:38.727863, 0 mins later

...
[2016-06-07 22:01:45,277] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_check_item: 4637e437-40c6-4c7c-84dc-464c3e7e6683 @2016-06-08 03:01:38
check item: 2016-06-07 22:00:38.727863, 1 mins later

...
[2016-06-07 22:02:51,807] INFO:huey.consumer.Worker:Worker-2:Executing queuecmd_check_item: 6bbaefac-7c24-4b99-8b16-29bc22b35b28 @2016-06-08 03:02:38
check item: 2016-06-07 22:00:38.727863, 2 mins later


[2016-06-07 22:03:34,476] INFO:huey.consumer.Scheduler:Scheduler:Scheduling periodic task queuecmd_perform_checks: queuecmd_perform_checks.
[2016-06-07 22:03:35,337] INFO:huey.consumer.Worker:Worker-2:Executing queuecmd_perform_checks: queuecmd_perform_checks
```

**Comment by chayim** [comment] 2016-06-08 13:12
Your logic is correct, and reflects exactly how I was doing this in my non-django enabled project. I'm thinking that the issue is (in some way) django integration. When queueing the tasks via the management command - that task too runs immediately, rather than queuing/honouring the huey queues.

I'm looking a bit further into that side now.

**Comment by coleifer** [comment] 2016-06-08 15:12
For sure, I just wanted to eliminate the possibility the bug was in the consumer or the core APIs.

**Comment by coleifer** [comment] 2016-06-08 16:25
Oh, you know what... I wonder about something. When you say the management command is running the tasks immediately, do you mean that the management command process is executing the huey tasks synchronously? Or do you mean the mgmt cmd is sending the tasks to the queue consumer, and the queue consumer itself is running them immediately?

**Comment by coleifer** [comment] 2016-06-08 16:59
Do you have DEBUG=True in your Django settings module by chance?

**Comment by coleifer** [comment] 2016-06-08 17:01
I used the same approach for the `django_ex` example code and can verify that it, too, is working correctly. I think this should rule out the possibility of a bug?

```
[2016-06-08 12:00:22,060] INFO:huey.consumer.Scheduler:Scheduler:Scheduling periodic task queuecmd_perform_checks: queuecmd_perform_checks.
[2016-06-08 12:00:23,549] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_perform_checks: queuecmd_perform_checks
scheduling check_item(0)
scheduling check_item(1)
scheduling check_item(2)
done enqueueing tasks
[2016-06-08 12:00:23,556] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_check_item: 2e45573c-3121-4ec8-8bbe-45c1964b8a9c @2016-06-08 17:00:23
check item: 2016-06-08 12:00:23.549548, 0 mins later
[2016-06-08 12:00:23,558] INFO:huey.consumer.Worker:Worker-1:Adding queuecmd_check_item: 3dcc1705-e4f1-48b1-b532-20de6c59cdc4 @2016-06-08 17:01:23 to schedule
[2016-06-08 12:00:23,560] INFO:huey.consumer.Worker:Worker-1:Adding queuecmd_check_item: df4e0fdc-30ee-481e-98c4-c7c896b2d11a @2016-06-08 17:02:23 to schedule
[2016-06-08 12:01:27,118] INFO:huey.consumer.Scheduler:Scheduler:Scheduling queuecmd_check_item: 3dcc1705-e4f1-48b1-b532-20de6c59cdc4 @2016-06-08 17:01:23 for execution
[2016-06-08 12:01:30,110] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_check_item: 3dcc1705-e4f1-48b1-b532-20de6c59cdc4 @2016-06-08 17:01:23
check item: 2016-06-08 12:00:23.549548, 1 mins later
[2016-06-08 12:02:27,170] INFO:huey.consumer.Scheduler:Scheduler:Scheduling queuecmd_check_item: df4e0fdc-30ee-481e-98c4-c7c896b2d11a @2016-06-08 17:02:23 for execution
[2016-06-08 12:02:27,895] INFO:huey.consumer.Worker:Worker-1:Executing queuecmd_check_item: df4e0fdc-30ee-481e-98c4-c7c896b2d11a @2016-06-08 17:02:23
check item: 2016-06-08 12:00:23.549548, 2 mins later
```

**Comment by coleifer** [comment] 2016-06-08 17:02
The timestamps are as follows:

* 12:00:23 - run the periodic command
* 12:00:23 - run the scheduled "check items" that was scheduled with an ETA of "now"
* 12:01:30 - run the scheduled "check items" that was scheduled with an ETA of now + 1 second
* 12:02:27 - run the now + 1 "check items"
* 12:03:23 (not shown, but repeats the loop)....

**Comment by coleifer** [comment] 2016-06-10 02:41
Whats up?

**Comment by coleifer** [comment] 2016-06-10 02:41
Closing for now, please comment with any updates and I'll re-open.

**Closed by coleifer** 2016-06-10 02:41 UTC
