### ISSUE TITLE
Restarting nicely with supervisord

### ISSUE THREAD

**Issue by miohtama** [coleifer/huey#88] opened 2015-02-08 02:58 UTC
I am  trying to make `supervisorctl restart` to work with huey. At the moment, restart doesn't kill the old process, but still creates another running huey instance. 

Below is a terminal capture showing huey is duplicated on restart:

    (venv)root@Ubuntu-1204-precise-64-minimal /srv/django/tatianastore # ps -Af|grep -i huey
    root     11260     1  0 03:46 ?        00:00:01 python manage.py run_huey --periodic
    root     13367  1166  0 03:55 ?        00:00:00 /bin/sh /srv/django/tatianastore/manage_wrapper.sh run_huey --periodic
    root     13370 13367  6 03:55 ?        00:00:00 python manage.py run_huey --periodic
    root     13378 10409  0 03:55 pts/1    00:00:00 grep --color=auto -i huey
    
    (venv)root@Ubuntu-1204-precise-64-minimal /srv/django/tatianastore # supervisorctl restart tatianastore_huey
    tatianastore_huey: stopped
    tatianastore_huey: started
    
    (venv)root@Ubuntu-1204-precise-64-minimal /srv/django/tatianastore # ps -Af|grep -i hueyroot     11260     1  0 03:46 ?        00:00:01 python manage.py run_huey --periodic
    root     13370     1  2 03:55 ?        00:00:00 python manage.py run_huey --periodic
    root     13401  1166  0 03:55 ?        00:00:00 /bin/sh /srv/django/tatianastore/manage_wrapper.sh run_huey --periodic
    root     13404 13401 14 03:55 ?        00:00:00 python manage.py run_huey --periodic
    root     13433 10409  0 03:55 pts/1    00:00:00 grep --color=auto -i huey

My supervisor config: https://github.com/miohtama/LibertyMusicStore/blob/master/conf/supervisor.conf

Which UNIX signal supervisor needs to send to huey in order to properly stop it? Or are there any special considerations regarding daemonizing huey process?

**Comment by coleifer** [comment] 2015-02-09 16:05
Hmm, I'm not sure as I haven't run into this particular bug before. Technically huey isn't ever daemonized, it just runs in the foreground and supervisor keeps an eye on it. I checked on my server and when I restarted the PID changed and there was only ever 1 instance running.

```
[program:blog_queue]
directory=/whatever/path/
command=/path/to/bin/huey_consumer.py blog.main.huey --logfile=/path/to/huey-blog.log -S 300
user=whoever
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/path/to/huey_supervisor.out.log
stderr_logfile=/path/to/huey_supervisor.out.err
environment=PYTHONPATH="/whatever:$PYTHONPATH"
```

**Comment by coleifer** [comment] 2015-02-09 20:52
I'm not quite sure what to do here...I'm unable to replicate this bug locally. Closing for now.

**Comment by miohtama** [comment] 2015-02-11 08:03
Thanks! I'll keep investigating why it doesn't restart properly. 

Just a question: What (should) happen if there is some periodical task running / hung and the process gets SIGTERM?

**Comment by coleifer** [comment] 2015-02-11 14:26
Actually that may be the problem... Huey will keep running until the long-running task finishes.

**Comment by miohtama** [comment] 2015-02-11 22:12
In my case, there should not be any long running tasks or those tasks should terminate eventually. However I have seen huey instances over few days old.

I'll try to dump the huey state using Python 3 faulthandler ( https://docs.python.org/3/library/faulthandler.html )

**Comment by coleifer** [comment] 2015-02-11 23:24
OK, that's good to know about the tasks in your app. I'll audit the code and see if I can find any issues.

**Comment by coleifer** [comment] 2015-02-11 23:24
One thing, do you mind sharing the invocation you use to start huey consumer?

**Comment by miohtama** [comment] 2015-02-12 01:38
Here is the exact supervisor config I am using (containing the invocation):

https://github.com/miohtama/LibertyMusicStore/blob/master/conf/supervisor.conf

**Comment by coleifer** [comment] 2015-02-12 04:39
Thanks @miohtama -- I'm going to take a look and see what I can see. When you run huey using the following invocation directly from the shell what happens when you press Ctrl+C?

```console
$ cd /srv/django/tatianastore
$ /srv/django/tatianastore/manage_wrapper.sh run_huey --periodic
# Wait til huey starts up, then press Ctrl+C.  What happens?
```

**Comment by coleifer** [comment] 2015-02-12 05:05
Alright I was able to replicate this locally and the issue is the fact that you're using a bash script to run the consumer. When I used a bash script to invoke the consumer, the consumer would continue running indefinitely. When I replaced the bash script with a direct invocation of the consumer, it worked as expected.

So, here is how I would suggest changing your config -- I believe this will accomplish the same thing as your wrapper:

```
[program:tatianastore_huey]
command=/srv/django/tatianastore/bin/python /srv/django/tatianastore/manage.py run_huey --periodic
```

**Closed by coleifer** 2015-02-12 05:05 UTC

**Comment by coleifer** [comment] 2015-02-12 05:09
More info: http://supervisord.org/subprocess.html#pidproxy-program

**Comment by miohtama** [comment] 2015-02-12 08:16
Ah, of course! I should have known this as I have run across the same issue couple of time during the years.

The rationale creating the (irritating) wrapper script is that `venv` module shipped with Python 3.4 on Ubuntu 12.04 is broken. It incorrectly fails to set `PYTHONPATH` and behaves differently than real `virtualenv`. Thus, one needs to run the script and source the environment. 

However the alternative solution is not to use `python -m venv` or supplied `virtualenv`, but simply install virtualenv from PyPi and override the system .deb installation.

**Comment by miohtama** [comment] 2015-02-12 08:20
Thanks for the help once again!

**Comment by coleifer** [comment] 2017-07-07 02:51
The info in this comment is a bit outdated:  when huey consumer receives SIGTERM, it **will not** wait for any currently-executing tasks to finish.
